services:
  warp:
    image: caomingjun/warp:latest
    container_name: yt2009-warp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "127.0.0.1:8088:80"
    environment:
      - WARP_SLEEP=2

  yt2009:
    build: .
    container_name: yt2009-app
    user: "root"
    restart: unless-stopped
    network_mode: "service:warp"
    depends_on:
      warp:
        condition: service_started
    environment:
      - YT2009_PORT=80
      - YT2009_ENV=dev
      - YT2009_IP=yt.faero.top
      - YT2009_AUTO_MAINTAIN=true
      - YT2009_MAINTAIN_MAX_SIZE=10
      - YT2009_MAINTAIN_MAX_CACHE_SIZE=15
    volumes:
      - ./assets:/yt2009/assets
      - ./data:/data
      - ./back/yt2009html.js:/yt2009/back/yt2009html.js
      - ./back/yt2009utils.js:/yt2009/back/yt2009utils.js
      - ./back/yt2009pot.js:/yt2009/back/yt2009pot.js
      - ./back/yt2009sabr.js:/yt2009/back/yt2009sabr.js
      - ./back/backend.js:/yt2009/back/backend.js
      - ./back/yt2009warpSWF.js:/yt2009/back/yt2009warpSWF.js
